version: '3'
services:
  db:
    container_name: Pokemon-Database
    image: mongo:5.0.0
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGODB_DATABSE: nest-pokemon
    volumes:
      - ./mongo:/data/db
